# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=4)),
                ('level', models.CharField(max_length=4)),
                ('period', models.IntegerField(default=0)),
                ('instructor', models.CharField(blank=True, max_length=40, null=True)),
                ('room', models.CharField(max_length=5)),
                ('reddot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_period', models.IntegerField(default=0)),
                ('period1class', models.IntegerField(default=0)),
                ('period2class', models.IntegerField(default=0)),
                ('period3class', models.IntegerField(default=0)),
                ('period4class', models.IntegerField(default=0)),
                ('period5class', models.IntegerField(default=0)),
                ('period6class', models.IntegerField(default=0)),
                ('period7class', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=7)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_nickname', models.CharField(max_length=20)),
                ('graduation_year', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
